import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'
import './globals.css'
import Header from '@/components/Layout/Header'
import { ThemeProvider } from 'next-themes'
import Footer from '@/components/Layout/Footer'

const bricolageGro = Bricolage_Grotesque({
  variable: '--font-bricolage-gro',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'PropertyPro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${bricolageGro.variable} bg-white dark:bg-badge antialiased`}>
        <ThemeProvider
          attribute='class'
          enableSystem={true}
          defaultTheme='light'>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
