import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'
import './globals.css'
import Header from '@/components/Layout/Header'

const bricolageGro = Bricolage_Grotesque({
  variable: '--font-bricolage-gro',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'PropertyPro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${bricolageGro.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
